packages:
  - frontend
  - backend/**
  - lightweight-otel-sdk
  - logger
  - utility
  - types

catalog:
  "@cloudflare/vitest-pool-workers": 0.8.59
  "@cloudflare/workers-types": 4.20250726.0
  drizzle-kit: 0.30.6
  drizzle-orm: 0.41.0
  esbuild-visualizer: 0.7.0
  neverthrow: 8.2.0
  npm-run-all2: 8.0.4
  typescript: 5.8.2
  vitest: 3.2.4
  wrangler: 4.26.0
  typescript-eslint: 8.40.0
  eslint: 9.34.0
  "@eslint/js": 9.34.0
  prettier: 3.6.2
