flowchart TD
  subgraph cron["Scheduled Site Workers"]
    entrypoint["@cfstackdemo/sitef-entrypoint<br/>cron起点・producer"]
    fetcher["@cfstackdemo/fetcher<br/>sale情報取得"]
    main["@cfstackdemo/sitef-main<br/>consumer (解析・保存)"]
  end

  subgraph queue["Cloudflare Queue"]
    cfqueue["Sale Queue"]
  end
  entrypoint --> fetcher
  fetcher --> cfqueue
  cfqueue --> main

  subgraph non-worker
    scraper["@cfstackdemo/sitef-scraper<br/>HTML Scraper"]
  end

  main --> scraper
  main --> d1Wrapper["@cfstackdemo/main-d1<br/>D1 Wrapper Worker"] --> d1[Cloudflare D1]
  main --> r2Wrapper["@cfstackdemo/main-r2<br/>R2 Wrapper Worker"] --> r2[Cloudflare R2]

  jwt-worker["@cfstackdemo/jwt-worker<br/>Auth Token Cache"]

  subgraph GCP
    gcpProxy["@cfstackdemo/gcp-request-relay<br/>GCP Proxy"]
  end

  mockServer["@cfstackdemo/mock-web-server<br/>Demo Target Server"]

  fetcher --> jwt-worker
  fetcher --> gcpProxy --> mockServer

  

  %% subgraph observability["Observability"]
  %%   otel["@ctstackdemo/lightweight-otel-sdk<br/><br/>Otel Tracing独自SDK"]
  %%   logger["@cfstackdemo/logger<br/>独自Logger"]
  %% end